import type { AppraisalCycle } from './cycleService';
import { DEFAULT_WEIGHTAGES, DEFAULT_RATING_RULES } from './cycleService';

export interface PerformanceMetrics {
    studentPassPercentage: number;
    averageStudentScore: number;
    attendancePercentage: number;
    studentFeedbackRating: number; // out of 5
    trainingHoursCompleted: number;
    trainingCoursesCompleted: number;
    lessonPlanCompliance: number; // percentage
    researchPublications: number;
    eventsParticipated: number;
}

export interface AutoEvaluationResult {
    overallRating: number; // 1-5 scale
    performanceBand: 'Outstanding' | 'Excellent' | 'Good' | 'Satisfactory' | 'Needs Improvement';
    recommendedIncrement: number; // percentage
    componentScores: {
        academic: number;
        professional: number;
        development: number;
        compliance: number;
    };
    strengths: string[];
    areasForImprovement: string[];
    autoGenerated: boolean;
    calculatedAt: string;
    predictedYearEndRating: number;
}


/**
 * Calculate academic performance score
 */
function calculateAcademicScore(metrics: PerformanceMetrics): number {
    const passScore = Math.min((metrics.studentPassPercentage / 100) * 5, 5);
    const avgScore = Math.min((metrics.averageStudentScore / 100) * 5, 5);
    const feedbackScore = metrics.studentFeedbackRating;

    return ((passScore * 0.4) + (avgScore * 0.3) + (feedbackScore * 0.3));
}

/**
 * Calculate professional development score
 */
function calculateProfessionalScore(metrics: PerformanceMetrics): number {
    const researchScore = Math.min(metrics.researchPublications * 1.5, 5);
    const lessonPlanScore = Math.min((metrics.lessonPlanCompliance / 100) * 5, 5);
    const eventsScore = Math.min(metrics.eventsParticipated * 0.5, 5);

    return ((researchScore * 0.4) + (lessonPlanScore * 0.4) + (eventsScore * 0.2));
}

/**
 * Calculate development score
 */
function calculateDevelopmentScore(metrics: PerformanceMetrics): number {
    const trainingHoursScore = Math.min((metrics.trainingHoursCompleted / 40) * 5, 5);
    const coursesScore = Math.min(metrics.trainingCoursesCompleted * 1.5, 5);

    return ((trainingHoursScore * 0.5) + (coursesScore * 0.5));
}

/**
 * Calculate compliance score
 */
function calculateComplianceScore(metrics: PerformanceMetrics): number {
    const attendanceScore = Math.min((metrics.attendancePercentage / 100) * 5, 5);
    const lessonPlanScore = Math.min((metrics.lessonPlanCompliance / 100) * 5, 5);

    return ((attendanceScore * 0.6) + (lessonPlanScore * 0.4));
}

/**
 * Determine performance band based on rule-based conditions
 */
function determinePerformanceBand(metrics: PerformanceMetrics, cycle?: AppraisalCycle): AutoEvaluationResult['performanceBand'] {
    const rules = cycle?.ratingRules || DEFAULT_RATING_RULES;

    // Check for Outstanding
    if (
        metrics.studentPassPercentage >= rules.outstanding.passPercentage &&
        metrics.attendancePercentage >= rules.outstanding.attendance &&
        metrics.studentFeedbackRating >= rules.outstanding.feedback &&
        metrics.trainingCoursesCompleted >= rules.outstanding.trainingCourses &&
        metrics.lessonPlanCompliance >= rules.outstanding.lessonPlan
    ) {
        return 'Outstanding';
    }

    // Check for Excellent
    if (
        metrics.studentPassPercentage >= rules.excellent.passPercentage &&
        metrics.attendancePercentage >= rules.excellent.attendance &&
        metrics.studentFeedbackRating >= rules.excellent.feedback &&
        metrics.trainingCoursesCompleted >= rules.excellent.trainingCourses &&
        metrics.lessonPlanCompliance >= rules.excellent.lessonPlan
    ) {
        return 'Excellent';
    }

    // Check for Good
    if (
        metrics.studentPassPercentage >= rules.good.passPercentage &&
        metrics.attendancePercentage >= rules.good.attendance &&
        metrics.studentFeedbackRating >= rules.good.feedback &&
        metrics.lessonPlanCompliance >= rules.good.lessonPlan
    ) {
        return 'Good';
    }

    // Check for Satisfactory
    if (
        metrics.studentPassPercentage >= rules.satisfactory.passPercentage &&
        metrics.attendancePercentage >= rules.satisfactory.attendance &&
        metrics.studentFeedbackRating >= rules.satisfactory.feedback &&
        metrics.lessonPlanCompliance >= rules.satisfactory.lessonPlan
    ) {
        return 'Satisfactory';
    }

    return 'Needs Improvement';
}

/**
 * Get recommended increment based on performance band
 */
function getRecommendedIncrement(band: AutoEvaluationResult['performanceBand']): number {
    const incrementMap: Record<AutoEvaluationResult['performanceBand'], number> = {
        'Outstanding': 15,
        'Excellent': 10,
        'Good': 7,
        'Satisfactory': 5,
        'Needs Improvement': 0
    };
    return incrementMap[band];
}

/**
 * Identify strengths based on metrics
 */
function identifyStrengths(metrics: PerformanceMetrics): string[] {
    const strengths: string[] = [];

    if (metrics.studentPassPercentage >= 90) {
        strengths.push('Exceptional student results with ' + metrics.studentPassPercentage + '% pass rate');
    }
    if (metrics.studentFeedbackRating >= 4.5) {
        strengths.push('Outstanding student feedback rating of ' + metrics.studentFeedbackRating + '/5');
    }
    if (metrics.trainingCoursesCompleted >= 2) {
        strengths.push('Highly committed to professional development with ' + metrics.trainingCoursesCompleted + ' training courses');
    }
    if (metrics.researchPublications >= 2) {
        strengths.push('Strong research contribution with ' + metrics.researchPublications + ' publications');
    }
    if (metrics.attendancePercentage >= 95) {
        strengths.push('Excellent attendance and punctuality');
    }
    if (metrics.lessonPlanCompliance >= 95) {
        strengths.push('Highly organized with ' + metrics.lessonPlanCompliance + '% lesson plan compliance');
    }

    return strengths.length > 0 ? strengths : ['Meets basic performance expectations'];
}

/**
 * Identify areas for improvement
 */
function identifyImprovements(metrics: PerformanceMetrics): string[] {
    const improvements: string[] = [];

    if (metrics.studentPassPercentage < 75) {
        improvements.push('Student pass percentage needs improvement (currently ' + metrics.studentPassPercentage + '%)');
    }
    if (metrics.studentFeedbackRating < 3.5) {
        improvements.push('Student feedback rating below expectations (currently ' + metrics.studentFeedbackRating + '/5)');
    }
    if (metrics.attendancePercentage < 80) {
        improvements.push('Attendance requires attention (currently ' + metrics.attendancePercentage + '%)');
    }
    if (metrics.trainingCoursesCompleted === 0) {
        improvements.push('Recommend completing at least one professional development training');
    }
    if (metrics.lessonPlanCompliance < 75) {
        improvements.push('Lesson plan compliance needs improvement');
    }
    if (metrics.researchPublications === 0) {
        improvements.push('Consider contributing to research publications');
    }

    return improvements.length > 0 ? improvements : ['Continue maintaining current performance standards'];
}

/**
 * Main automated evaluation function
 */
export function calculateAutomatedEvaluation(metrics: PerformanceMetrics, cycle?: AppraisalCycle): AutoEvaluationResult {
    // Calculate component scores
    const academicScore = calculateAcademicScore(metrics);
    const professionalScore = calculateProfessionalScore(metrics);
    const developmentScore = calculateDevelopmentScore(metrics);
    const complianceScore = calculateComplianceScore(metrics);

    // Use cycle weightages if available, otherwise fallback to defaults
    const weightages = cycle?.weightages || DEFAULT_WEIGHTAGES;

    // Map KRA categories to engine components
    // Map Academic category to academic
    // Map Learning & Development to development
    // Map Compliance to compliance
    // use others for professional
    const activeWeightages = {
        academic: weightages['Academic'] || 40,
        professional: weightages['Professional Conduct'] || weightages['Leadership'] || weightages['Research'] || 30,
        development: weightages['Learning & Development'] || 20,
        compliance: weightages['Compliance'] || weightages['Administrative'] || 10
    };

    // Calculate weighted overall rating
    const overallRating = (
        (academicScore * activeWeightages.academic / 100) +
        (professionalScore * activeWeightages.professional / 100) +
        (developmentScore * activeWeightages.development / 100) +
        (complianceScore * activeWeightages.compliance / 100)
    );

    // Determine performance band using rule-based logic
    const performanceBand = determinePerformanceBand(metrics, cycle);

    // Get recommended increment
    const recommendedIncrement = getRecommendedIncrement(performanceBand);

    // Identify strengths and improvements
    const strengths = identifyStrengths(metrics);
    const areasForImprovement = identifyImprovements(metrics);

    // Predict year-end rating (assuming current trend continues)
    const predictedYearEndRating = Math.min(overallRating * 1.05, 5); // 5% optimistic projection

    return {
        overallRating: Math.round(overallRating * 10) / 10,
        performanceBand,
        recommendedIncrement,
        componentScores: {
            academic: Math.round(academicScore * 10) / 10,
            professional: Math.round(professionalScore * 10) / 10,
            development: Math.round(developmentScore * 10) / 10,
            compliance: Math.round(complianceScore * 10) / 10
        },
        strengths,
        areasForImprovement,
        autoGenerated: true,
        calculatedAt: new Date().toISOString(),
        predictedYearEndRating: Math.round(predictedYearEndRating * 10) / 10
    };
}

/**
 * Detect performance anomalies (sudden drops)
 */
export function detectAnomalies(
    currentMetrics: PerformanceMetrics,
    previousMetrics: PerformanceMetrics
): { hasAnomaly: boolean; alerts: string[] } {
    const alerts: string[] = [];

    // Check for significant drops (>15%)
    if (currentMetrics.studentPassPercentage < previousMetrics.studentPassPercentage - 15) {
        alerts.push('Significant drop in student pass percentage detected');
    }
    if (currentMetrics.studentFeedbackRating < previousMetrics.studentFeedbackRating - 0.5) {
        alerts.push('Notable decline in student feedback rating');
    }
    if (currentMetrics.attendancePercentage < previousMetrics.attendancePercentage - 10) {
        alerts.push('Attendance has decreased significantly');
    }

    return {
        hasAnomaly: alerts.length > 0,
        alerts
    };
}

/**
 * Mock data for testing
 */
export const getMockMetrics = (): PerformanceMetrics => {
    return {
        studentPassPercentage: 87,
        averageStudentScore: 78,
        attendancePercentage: 92,
        studentFeedbackRating: 4.3,
        trainingHoursCompleted: 32,
        trainingCoursesCompleted: 2,
        lessonPlanCompliance: 95,
        researchPublications: 1,
        eventsParticipated: 3
    };
};
